spring:
  web:
    cors:
      allowed-origins: "http://localhost:4200, http://unfold.fit"
      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  datasource:
    url: jdbc:mysql://68.178.236.157:3306/unfoldfit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: unfoldfit
    password: unfoldfit@123
#    url: jdbc:mysql://localhost:3307/unfold_schema
#    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
